### ISSUE TITLE
Nombre del package en el archivo Product

### ISSUE THREAD

**Issue by jackgris** [gophers-latam/small-template#1]
En el template el nombre del paquete que esta en el archivo products.go deberia coincidir con la carpeta que lo contiene.

Una opcion podria ser cambiar el nombre de domain a models, la otra y por la es que dentro de domain tenga una carpeta models que contenga a products.go

**Comment by Joziaz** [comment]
Le cambie el nombre y olvide actualizar el package 😅, en este caso la idea es que el package fuera domain y a medida que crezca si el usario ve que es necesiario agregar la caperta y paquete de models dentro de domain.

**Comment by jackgris** [comment]
Ok, si, eso era de lo que no estaba seguro, que preferias para este proyecto.

**Comment by Joziaz** [comment]
Si, es que fue la concesión a la que llegamos cuando se propusieron los templates.
